### ISSUE TITLE
Grid margins and unit sizing

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/lists-n-grids#1]
@muxlowc 

I'm not sure how to add empty space to the left side of the grid as shown in the screenshots. Also, I believe I'm supposed to make the cards themselves smaller. I've tried using max-length-no-center on the units but maybe I'm supposed to apply that class to a different element?

**Comment by MacKenzieRose** [comment]
Hi!

To get the spacing between the cards and the edge of your page, you'll want to add a gutter to your `<ol>` classes.

To make the cards themselves smaller, you'll need to add a `<div>` inside your `<li>` tags, and apply your card styling there. I would also highly recommend removing the `push push-r-1-2` classes, as they are adding margin to your cards, which means they won't sit beside each other, even when `m-1-2 l-1-2` etc are applied.

Let us know how that goes.

Cheers!
MacKenzie

**Comment by briannaneet** [comment]
@MacKenzieRose thank you, I did what you recommended and my cards are sitting beside each other now.
