### ISSUE TITLE
Unit utilities/alignment and matching spacing

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/lists-n-grids#2]
@muxlowc
I'm having problems with spacing on the top part between the h1 and the cards. I've tried to play around with "push" classes to the h1 but I haven't been successful in matching that part. 

<img width="321" alt="Screen Shot 2020-04-17 at 11 44 08 PM" src="https://user-images.githubusercontent.com/55240989/79627339-63f45d00-8105-11ea-8f25-86f57cca90de.png">

I've also added content-fill, grid-stretch, and unit-content-distribute to meet the markbot requirements, but I'm not seeing any change to the grid or units, so I'm unsure of where I should be adding those classes.

**Comment by muxlowc** [comment]
@briannaneet instead of push-2-3 on your h1, have you tried using push-1-2?

You will also probably want to remove your content-fill from your li, and only have it on the div directly inside it, and the p tag

```
      <li class="unit xs-1 s-1 m-1-2 l-1-2 island-1-4 push-1-2 unit-content-distribute">
        <div class="card island-1-2 content-fill unit-content-distribute">
          <img class="img-flex push-1-2" src="images/arsinoitherium.jpg" alt="">
          <h2 class="push-1-2 giga">Arsinoitherium</h2>
          <p class="push-1-2 content-fill">
```

Hope that helps!

**Comment by briannaneet** [comment]
@muxlowc thank you, that definitely helped!
