### ISSUE TITLE
Matching spacing between cards

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/lists-n-grids#3]
@muxlowc

I was wondering how I should reduce the spacing between these two cards on the larger screen sizes (m, l and xl) to match the screenshot without affecting the spacing on the small screen size (xs and small match very close). I tried a few different things yesterday but I had no luck.

Mine:
<img width="608" alt="Screen Shot 2020-04-21 at 9 59 47 PM" src="https://user-images.githubusercontent.com/55240989/79932632-f8b7cd00-841b-11ea-8754-de17db821fee.png">

Screenshot:
<img width="608" alt="Screen Shot 2020-04-21 at 9 59 52 PM" src="https://user-images.githubusercontent.com/55240989/79932689-14bb6e80-841c-11ea-977d-b416ad436d94.png">

**Comment by muxlowc** [comment]
@briannaneet - oh so close!

1) on your cards, change the "max-lenght-no-center" to "unit-content-distribute",
2) on your li's change your gutter from 1-2 to 1-4, 
3) add gutter-1-4 to your `<ol>`

Hope that helps!

**Comment by briannaneet** [comment]
Thank you, the gutter on the li's and ol makes a lot of sense.
